//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/GlobalInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GlobalInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GlobalInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GlobalInput"",
    ""maps"": [
        {
            ""name"": ""GlobalControls"",
            ""id"": ""7561e4e4-f331-45a6-9f41-a165d1bd6480"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""5785e323-f880-4832-8852-810527849c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8cd558fe-2601-4465-9ca4-27832fc56db9"",
                    ""path"": ""<OculusTouchController>/start"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GlobalControls
        m_GlobalControls = asset.FindActionMap("GlobalControls", throwIfNotFound: true);
        m_GlobalControls_Menu = m_GlobalControls.FindAction("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GlobalControls
    private readonly InputActionMap m_GlobalControls;
    private IGlobalControlsActions m_GlobalControlsActionsCallbackInterface;
    private readonly InputAction m_GlobalControls_Menu;
    public struct GlobalControlsActions
    {
        private @GlobalInput m_Wrapper;
        public GlobalControlsActions(@GlobalInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_GlobalControls_Menu;
        public InputActionMap Get() { return m_Wrapper.m_GlobalControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GlobalControlsActions set) { return set.Get(); }
        public void SetCallbacks(IGlobalControlsActions instance)
        {
            if (m_Wrapper.m_GlobalControlsActionsCallbackInterface != null)
            {
                @Menu.started -= m_Wrapper.m_GlobalControlsActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_GlobalControlsActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_GlobalControlsActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_GlobalControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public GlobalControlsActions @GlobalControls => new GlobalControlsActions(this);
    public interface IGlobalControlsActions
    {
        void OnMenu(InputAction.CallbackContext context);
    }
}
