//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""DogControls"",
            ""id"": ""7561e4e4-f331-45a6-9f41-a165d1bd6480"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Value"",
                    ""id"": ""82a39427-51f1-46a3-b30a-9dd6a7fd9c10"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Value"",
                    ""id"": ""37bb8c37-79c3-455f-8af5-82783b4757af"",
                    ""expectedControlType"": ""Key"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalAcceleleration"",
                    ""type"": ""Value"",
                    ""id"": ""1c8900d9-90cf-4362-b8e5-ab1bb05f38c8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""1a396470-6e1e-4689-9162-f26396581ee3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fab5ae0d-ef16-42c4-bc97-ee2f6da6fb0f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6f83aea-6274-48e0-9920-276e48f0a0bc"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6bb8bf8-5fcf-485c-aae5-53d5c338258a"",
                    ""path"": ""<LinearAccelerationSensor>/acceleration/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAcceleleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50dc821a-dd87-4286-98b1-57abf1adff01"",
                    ""path"": ""<Accelerometer>/acceleration/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DogControls
        m_DogControls = asset.FindActionMap("DogControls", throwIfNotFound: true);
        m_DogControls_Up = m_DogControls.FindAction("Up", throwIfNotFound: true);
        m_DogControls_Down = m_DogControls.FindAction("Down", throwIfNotFound: true);
        m_DogControls_VerticalAcceleleration = m_DogControls.FindAction("VerticalAcceleleration", throwIfNotFound: true);
        m_DogControls_Acceleration = m_DogControls.FindAction("Acceleration", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DogControls
    private readonly InputActionMap m_DogControls;
    private List<IDogControlsActions> m_DogControlsActionsCallbackInterfaces = new List<IDogControlsActions>();
    private readonly InputAction m_DogControls_Up;
    private readonly InputAction m_DogControls_Down;
    private readonly InputAction m_DogControls_VerticalAcceleleration;
    private readonly InputAction m_DogControls_Acceleration;
    public struct DogControlsActions
    {
        private @PlayerInput m_Wrapper;
        public DogControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_DogControls_Up;
        public InputAction @Down => m_Wrapper.m_DogControls_Down;
        public InputAction @VerticalAcceleleration => m_Wrapper.m_DogControls_VerticalAcceleleration;
        public InputAction @Acceleration => m_Wrapper.m_DogControls_Acceleration;
        public InputActionMap Get() { return m_Wrapper.m_DogControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DogControlsActions set) { return set.Get(); }
        public void AddCallbacks(IDogControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_DogControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DogControlsActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @VerticalAcceleleration.started += instance.OnVerticalAcceleleration;
            @VerticalAcceleleration.performed += instance.OnVerticalAcceleleration;
            @VerticalAcceleleration.canceled += instance.OnVerticalAcceleleration;
            @Acceleration.started += instance.OnAcceleration;
            @Acceleration.performed += instance.OnAcceleration;
            @Acceleration.canceled += instance.OnAcceleration;
        }

        private void UnregisterCallbacks(IDogControlsActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @VerticalAcceleleration.started -= instance.OnVerticalAcceleleration;
            @VerticalAcceleleration.performed -= instance.OnVerticalAcceleleration;
            @VerticalAcceleleration.canceled -= instance.OnVerticalAcceleleration;
            @Acceleration.started -= instance.OnAcceleration;
            @Acceleration.performed -= instance.OnAcceleration;
            @Acceleration.canceled -= instance.OnAcceleration;
        }

        public void RemoveCallbacks(IDogControlsActions instance)
        {
            if (m_Wrapper.m_DogControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDogControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_DogControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DogControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DogControlsActions @DogControls => new DogControlsActions(this);
    public interface IDogControlsActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnVerticalAcceleleration(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
    }
}
